name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags:
    - '*'
  workflow_dispatch:

jobs:
  rust:
    name: deno_media_type-ubuntu-latest-release
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      CARGO_INCREMENTAL: 0
      GH_ACTIONS: 1
      RUST_BACKTRACE: full
      RUSTFLAGS: -D warnings

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: dsherret/rust-toolchain-file@v1

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Format
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --all-targets --all-features

      - name: Build
        run: cargo build --all-targets --all-features
      - name: Build --no-default-features
        run: cargo build --no-default-features
      - name: Build (data_url)
        run: cargo build --no-default-features --features data_url
      - name: Build (decoding)
        run: cargo build --no-default-features --features decoding
      - name: Test
        run: cargo test --all-targets --all-features

      - name: Publish
        if: |
          github.repository == 'denoland/deno_media_type' &&
          startsWith(github.ref, 'refs/tags/')
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish
